### ISSUE TITLE
I saw that there are only 8 points for focal length and principal point for intrinsics. What do these points correspond to ? Could you also explain where the point cloud data is?

### ISSUE THREAD

**Issue by patrick0701** [facebookresearch/replay_dataset#1]
![7d53a5cee17305dcb6a1eb7c1ede3af](https://github.com/facebookresearch/replay_dataset/assets/61094053/9e3d1943-71ec-4d05-8c0a-3eaac906be74)
![b92f2b09013def19d7c548fa4be2da3](https://github.com/facebookresearch/replay_dataset/assets/61094053/3e3bb44a-1d31-485f-bc9d-d492149053ab)

**Comment by shapovalov** [comment]
Hello and sorry for the delay.
I don’t think you unpack the tuples correctly. Each of the fields should be a pair of float32 numbers.
The easiest way to access the data is using Pytorch3D. See examples of how to create a dataset object here: https://github.com/facebookresearch/replay_dataset/blob/main/tests/test_replay_dataset.py

Then, items of the dataset will contain the `camera` field that includes the correctly loaded intrinsics and extrinsics.
If you want to avoid using PyTorch3D datasets, you should use SqlAlchemy 2.0 with these ORM types: https://github.com/facebookresearch/replay_dataset/blob/main/replay_dataset/replay_orm_types.py

The byte unpacking is defined in those. This code shows how PyTorch3D dataset loads those: https://github.com/facebookresearch/pytorch3d/blob/292acc71a33bf389225ef02af237dd82a8319f59/pytorch3d/implicitron/dataset/sql_dataset.py#L239

**Comment by hausenshi** [comment]
Can you post the code for reading the camera intrinsics? We are running on deadlines. Thanks!

**Comment by shapovalov** [comment]
Can you explain what did not work with the approach I suggested?
If you want to avoid PerspectiveCameras for some reason, you can use this code like this to read rows to a pandas data frame:

```
import torch
import sqlalchemy as sa
import pandas as pd
from replay_dataset.replay_orm_types import ReplayFrameAnnotation

metadata_file = <YOUR PATH>

sql_engine = sa.create_engine(
    f"sqlite:///file:{metadata_file}?mode=ro&uri=true"
)

stmt = sa.select(ReplayFrameAnnotation).limit(10)
with sql_engine.connect() as connection:
    frames = pd.read_sql_query(stmt, connection)
```

Note that the focal length and principal point are in NDC format (the shorter image side is [−1, 1]).

**Comment by hausenshi** [comment]
Thank you for the code! We've already tried to use select statement of sqlalchemy. It's the binary unpacking that we try to figure out. Do we unpack with python array and assume they are all floats? This is the data from one video clip. It looks like the source and target viewpoints have different definitions of data. Can you help us with this?

{'_image_size': [(3.026804682941605e-42, 5.3809861030072976e-42)],
 '_viewpoint_R': [(-0.6106827259063721,
   0.20946836471557617,
   0.7636685371398926,
   -0.3228195607662201,
   -0.9464594125747681,
   0.001457414822652936,
   0.7230865359306335,
   -0.24563713371753693,
   0.6456068754196167)],
 '_viewpoint_T': [(0.3888905346393585,
   -0.05810976028442383,
   5.746898651123047)],
 '_viewpoint_focal_length': [(2.997899293899536, 3.0517170429229736)],
 '_viewpoint_principal_point': [(0.026272470131516457, 0.03673796355724335)]}

**Comment by shapovalov** [comment]
This looks about right, saving for image_size (that should be integers) and the reshaping of R.
I really recommend you to use our implementations – the snippet above is short and has minimum dependencies, if you cannot use the official data loaders for some reason.

> It looks like the source and target viewpoints have different definitions of data.

Please elaborate on what the problem is. Again, the result looks mostly right.

**Comment by hausenshi** [comment]
We have figured it out. Thank you!
